// Mocks generated by Mockito 5.1.0 from annotations
// in tv_shows/test/providers/write_review_provider_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;
import 'dart:ui' as _i14;

import 'package:flutter/cupertino.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tv_shows/common/request_state.dart' as _i4;
import 'package:tv_shows/models/review.dart' as _i3;
import 'package:tv_shows/models/review_provider.dart' as _i12;
import 'package:tv_shows/models/show.dart' as _i9;
import 'package:tv_shows/models/user.dart' as _i2;
import 'package:tv_shows/net/network_repository.dart' as _i5;
import 'package:tv_shows/net/requests/add_review.dart' as _i10;
import 'package:tv_shows/net/requests/register_info.dart' as _i7;
import 'package:tv_shows/net/requests/sign_in_info.dart' as _i8;
import 'package:tv_shows/net/requests/update_email.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeUser_0 extends _i1.Fake implements _i2.User {}

class _FakeReview_1 extends _i1.Fake implements _i3.Review {}

class _FakeRequestState_2<Value, Error extends Exception> extends _i1.Fake
    implements _i4.RequestState<Value, Error> {}

/// A class which mocks [NetworkRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkRepository extends _i1.Mock implements _i5.NetworkRepository {
  MockNetworkRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.User> registerUser(_i7.RegisterInfo? info) =>
      (super.noSuchMethod(Invocation.method(#registerUser, [info]),
              returnValue: Future<_i2.User>.value(_FakeUser_0()))
          as _i6.Future<_i2.User>);
  @override
  _i6.Future<_i2.User> signInUser(_i8.SignInInfo? info) =>
      (super.noSuchMethod(Invocation.method(#signInUser, [info]),
              returnValue: Future<_i2.User>.value(_FakeUser_0()))
          as _i6.Future<_i2.User>);
  @override
  _i6.Future<List<_i9.Show>> fetchShows() =>
      (super.noSuchMethod(Invocation.method(#fetchShows, []),
              returnValue: Future<List<_i9.Show>>.value(<_i9.Show>[]))
          as _i6.Future<List<_i9.Show>>);
  @override
  _i6.Future<List<_i3.Review>> fetchShowReviews(String? showID) =>
      (super.noSuchMethod(Invocation.method(#fetchShowReviews, [showID]),
              returnValue: Future<List<_i3.Review>>.value(<_i3.Review>[]))
          as _i6.Future<List<_i3.Review>>);
  @override
  _i6.Future<_i3.Review> addShowReview(_i10.AddReview? body) =>
      (super.noSuchMethod(Invocation.method(#addShowReview, [body]),
              returnValue: Future<_i3.Review>.value(_FakeReview_1()))
          as _i6.Future<_i3.Review>);
  @override
  _i6.Future<_i2.User> updateEmail(_i11.UpdateEmail? body) =>
      (super.noSuchMethod(Invocation.method(#updateEmail, [body]),
              returnValue: Future<_i2.User>.value(_FakeUser_0()))
          as _i6.Future<_i2.User>);
  @override
  _i6.Future<_i2.User> updateProfilePhoto(String? imagePath) =>
      (super.noSuchMethod(Invocation.method(#updateProfilePhoto, [imagePath]),
              returnValue: Future<_i2.User>.value(_FakeUser_0()))
          as _i6.Future<_i2.User>);
}

/// A class which mocks [ReviewProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockReviewProvider extends _i1.Mock implements _i12.ReviewProvider {
  MockReviewProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get showID =>
      (super.noSuchMethod(Invocation.getter(#showID), returnValue: '')
          as String);
  @override
  set showID(String? _showID) =>
      super.noSuchMethod(Invocation.setter(#showID, _showID),
          returnValueForMissingStub: null);
  @override
  _i4.RequestState<List<_i3.Review>, Exception> get state =>
      (super.noSuchMethod(Invocation.getter(#state),
              returnValue: _FakeRequestState_2<List<_i3.Review>, Exception>())
          as _i4.RequestState<List<_i3.Review>, Exception>);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  void fetchReviews() =>
      super.noSuchMethod(Invocation.method(#fetchReviews, []),
          returnValueForMissingStub: null);
  @override
  _i6.Future<void> executeRequest(
          {_i13.ValueGetter<_i6.Future<List<_i3.Review>>>? requestBuilder,
          Exception? Function(Exception)? errorHandler}) =>
      (super.noSuchMethod(
          Invocation.method(#executeRequest, [],
              {#requestBuilder: requestBuilder, #errorHandler: errorHandler}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void reset() => super.noSuchMethod(Invocation.method(#reset, []),
      returnValueForMissingStub: null);
  @override
  void addListener(_i14.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i14.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
